---
#Transfer mysql file to nodes,and configure the mysql.

- name: Copy mysql software
  copy: src=mysql.tar.gz dest=/usr/local/mysql.tar.gz

- name: Uncompress mysql software
  shell: tar xzf /usr/local/mysql.tar.gz -C /usr/local/

#- name:  Uncompress mysql software
#  unarchive: src=files/mysql.tar.gz dest=/usr/local

- name: Transfer mysql start script
  template: src=mysqld dest=/etc/init.d/mysqld owner=root group=root mode=0755
