---
# some dependent packages.
- name: Install initalizate nginx required package
  yum: name={{ item }} state=installed
  with_items:
    - gcc
    - wget
    - zlib-devel
    - pcre-devel
    - perl
    - perl-devel
    - libaio
    - libaio-devel
- name: Install mysql required package
  yum: name="compat-libstdc++-33" state=installed
